name: CI-CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t app:test .

      - name: Run Tests
        run: docker run app:test npm test

  publish:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-ci:latest ${{ github.workspace }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-ci:latest

  sonar:
    needs: build-test
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: Bas557169_AUY1102-Pipeline
          SONAR_ORGANIZATION: bas557169
  
  snyk:
    needs: build-test
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: snyk/actions/node@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  codeql:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@v3

  scout:
    needs: publish
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: docker/scout-action@v1
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/app-ci:latest
          command: cves

  bloquear:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Bloqueo de despliegue
        run: echo "Se detectaron vulnerabilidades cr√≠ticas. Despliegue bloqueado."

